services:
  rabbitmq:
    image: "rabbitmq:management"  # используем образ с включенным управлением
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для управляющего интерфейса